name: EPA Deployment

on: 'push'
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Sync files to server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 192.249.121.28
        username: admin@admin.developmentpermit.com.gh
        password: o$nCX4+LD$)d

        
